# Netlify configuration file
[build]
  # No build process needed for static site
  publish = "."

[build.environment]
  # Environment variables (if needed)
  
[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # YAML file headers
  for = "*.yaml"
  
# Form handling configuration
[forms]
  # Form with name "contact" (must match form name attribute in HTML)
  [forms.contact]
    # Success page after form submission
    success_url = "/form-success.html"
    # Set to true to receive email notifications
    email_notifications = true
  [headers.values]
    Content-Type = "text/yaml"

[[headers]]
  # Video file headers
  for = "*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Image file headers
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect rules (if needed)
[[redirects]]
  from = "/admin/*"
  to = "/404.html"
  status = 404
